spring:
  application:
    name: ratechanger
  datasource:
    url: ${JDBC_CONNECTION_STRING}
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

server:
  port: ${PORT}
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:keystore/ratechanger.p12
    key-store-password: ratechanger
    key-alias: ratechanger

exchange-rates-api:
  baseUrl: ${EXCHANGE_RATES_API_BASE_URL}
  apiKey: ${EXCHANGE_RATES_API_KEY}
  currencies:
    - GBP
    - USD
    - HKD